import { z } from 'zod'
import { numericString } from '../../common/scheme.ts'
import { PREFIX } from '../../const.ts'

// {
//     "ig": null,
//     "im": null,
//     "ic": null,
//     "iv": null,
//     "trml_Cd": "1242001",
//     "trml_Nm": "가평",
//     "cty_Bus_Area_Cd": "03",
//     "cty_Bus_Area_Nm": "경기도",
//     "hmpg_Exps_Yn": "Y",
//     "hmpg_Tisu_Psb_Yn": "Y",
//     "return_Yn": null,
//     "pre_Trml_Cd": null,
//     "rtnGbn": null,
//     "cardGbn": null,
//     "bef_Aft_Dvs": null,
//     "req_Rec_Num": null,
//     "req_Pgm_Dvs": null,
//     "depr_Trml_Cd": null,
//     "arvl_Trml_Cd": null,
//     "depr_Dt": null,
//     "depr_Time": null,
//     "atl_Depr_Dt": null,
//     "atl_Depr_Time": null,
//     "atl_Depr_Dt_Fmt": null,
//     "atl_Depr_Time_Fmt": null,
//     "page_No": null,
//     "page_Inf_Num": null,
//     "rt_Depr_Dt": null,
//     "rt_Depr_Time": null,
//     "depr_Trml_Nm": null,
//     "arvl_Trml_Nm": null,
//     "bus_Cacm_Cd": null,
//     "bus_Cls_Cd": null,
//     "bus_Cacm_Nm": null,
//     "bus_Cls_Nm": null,
//     "rot_Id": null,
//     "rot_Sqno": null,
//     "alcn_Dt": null,
//     "alcn_Dt_Fmt": null,
//     "alcn_Sqno": null,
//     "sats_Num": null,
//     "rmn_Scnt": null,
//     "dc_Psb_Yn": null,
//     "pcpy_Dvs": null,
//     "pcpy_Num": null,
//     "sats_No": null,
//     "bus_Tck_Knd_Cd": null,
//     "total": null,
//     "sats_Pcpy_Id": null,
//     "cty_Bus_Dc_Knd_Cd": null,
//     "dcrt_Dvs_Cd": null,
//     "rtrp_Depr_Dt": null,
//     "card1": null,
//     "card2": null,
//     "card_No1": null,
//     "card_No2": null,
//     "card_No3": null,
//     "card_No4": null,
//     "month": null,
//     "year": null,
//     "card_Pwd": null,
//     "brdt": null,
//     "cmpNo1": null,
//     "cmpNo2": null,
//     "cmpNo3": null,
//     "mrsp_Brdt": null,
//     "mrsp_Tel_No1": null,
//     "mrsp_Tel_No2": null,
//     "mrsp_Tel_No3": null,
//     "mrs_Num": null,
//     "dc_Total": null,
//     "ogn_Total": null,
//     "bef_Total": null,
//     "atl_Depr_Dt_S1": null,
//     "atl_Depr_Time_S1": null,
//     "pcpyCanc": null,
//     "cty_Bus_Sys_Dvs_Cd": "E",
//     "test1": null,
//     "card_Co": null,
//     "appPwd": null,
//     "sms_Chk": null,
//     "vtrn_No": null
// },

// 의미 없는 필드들은 삭제하고, 실제 값이 있는 필드들만 남겨야 함

export const rawTmoneyTerminalScheme = z
    .object({
        trml_Cd: numericString,
        trml_Nm: z.string(),
        cty_Bus_Area_Cd: numericString,
        cty_Bus_Area_Nm: z.string(),
    })
    .transform((d) => ({
        id: PREFIX.TMONEY + d.trml_Cd,
        name: d.trml_Nm,
        area: d.cty_Bus_Area_Cd,
    }))
