name: Scheduled Data Update

on:
    schedule:
        # 30분마다 실행
        - cron: '*/30 * * * *'
    # 수동으로 워크플로우를 실행할 수 있도록 추가
    workflow_dispatch:
        inputs:
            Samples:
                required: true
                default: '20'
            Repetitions:
                required: true
                default: '7'
                description: 'Number of times to repeat the update process'

jobs:
    update-data:
        runs-on: ubuntu-latest
        steps:
            - name: Set Timezone
              uses: szenius/set-timezone@v2.0
              with:
                  timezoneLinux: 'Asia/Seoul'
                  timezoneMacos: 'Asia/Seoul'
                  timezoneWindows: 'Korea Standard Time'

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  # Git 하위 모듈이 사용된 것 같으므로 하위 모듈도 체크아웃합니다
                  submodules: 'recursive'
                  # 전체 히스토리를 가져옵니다 (Git 작업에 필요)
                  fetch-depth: 0
                  persist-credentials: false

            - name: Set up Git credentials
              run: |
                  git config --global user.name "rycont"
                  git config --global user.email "reactdev@kakao.com"

            - name: Set up submodule push URL with token
              run: |
                  git config --global url."https://${{ secrets.MY_GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

                  cd kobus-output
                  git remote set-url origin https://${{ secrets.MY_GITHUB_TOKEN }}:x-oauth-basic@github.com/rycont/operation-plan-kobus.git
                    
                  cd ../bustago-output
                  git remote set-url origin https://${{ secrets.MY_GITHUB_TOKEN }}:x-oauth-basic@github.com/rycont/operation-plan-bustago.git

                  # 원래 디렉토리로 복귀
                  cd ..

            - name: Install Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.x

            - name: Switch submodules to main branch
              run: |
                  cd kobus-output
                  git switch main
                  cd ../bustago-output
                  git switch main

            - uses: browser-actions/setup-chrome@v1
              id: setup-chrome

            - name: Run update script ${{ github.event.inputs.Repetitions || 5
7 }} times
              run: |
                  for i in {1..${{ github.event.inputs.Repetitions || 7 }}}; do
                      echo "Executing run $i of ${{ github.event.inputs.Repetitions || 7 }}"
                      deno run -A --unstable-temporal sampling-update.ts || echo "Run $i failed, continuing to next run"
                      sleep 5  # Adding a small pause between runs
                  done
              env:
                  CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
                  UPDATE_SAMPLES: ${{ github.event.inputs.Samples || 20 }}

            - name: Push to GitHub
              run: |
                  cd kobus-output
                  git add -A
                  git commit -m "Regular Data Update(Kobus)"
                  git push origin
                  cd ../bustago-output
                  git add -A
                  git commit -m "Regular Data Update(Bustago)"
                  git push origin
                  cd ..
                  git add -A
                  git commit -m "Regular Data Update(Workspace)"
                  git push origin
